apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-tracker-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: habit-tracker-auth
  template:
    metadata:
      labels:
        app: habit-tracker-auth
    spec:
      containers:
      - name: habit-tracker-auth
        image: xelfarnab/authentication-service:latest
        ports:
        - containerPort: 80
